### ISSUE TITLE
Issue from 07/21/15

### ISSUE THREAD

**Issue by mverdmann** [pyIPP/ideview#3]
ecrhpos (u,l) and ecrhmax in rho-contour (as crosses because of the zero-problem)
guess: b = backend.getSinglePlotForTimePoint('contour-ecrhpos', 2.5)
           plt.plot(b.data[5]['x'], b.data[5]['y'], 'x')

lower priorities: Vol and ikCAT as traces

**Comment by mverdmann** [comment]
Issue solved (all but low prios)
new Issue: 1 t-line in q-timecontour stays after pressing playbutton

**Comment by bpwned** [comment]
fixed, must not use outer loop variable i for inner loops (in this case, q label iteration).
